app/urls.py
from django.urls import path 
from . import views 
 
app_name = 'app' 
urlpatterns = [
    path('', views.index, name='index'), 
    path('login/', views.form_iniciar_sesion, name='form_iniciar_sesion'), 
    path('login_post/', views.iniciar_sesion, name='iniciar_sesion'), 
    path('logout/', views.cerrar_sesion, name='cerrar_sesion'), 

    path('categorias/', views.categorias, name='categorias'), 
    path('categorias/<int:id>/', views.categoria, name='categoria'), 

    path('categorias/crear/', views.form_crear_categoria, name='form_crear_categoria'),
     
    path('categorias/crear_post/', views.crear_categoria_post, name='crear_categoria_post'), 

    path('peliculas/', views.peliculas, name='peliculas'), 
    path('peliculas/crear/', views.form_crear_pelicula, name='form_crear_pelicula'),
    path('peliculas/crear_post/', views.crear_pelicula_post, name='crear_pelicula_post'), 

]

blockbuster/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models

class Categoria(models.Model):
    nombre = models.CharField(max_length=100, null=False)
    descripcion = models.TextField(null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        app_label = 'app'


class Pelicula(models.Model):
    titulo = models.CharField(max_length=500, null=False)
    year = models.IntegerField(null=True)
    categoria = models.ForeignKey(
        Categoria, 
        related_name='peliculas', 
        null=False, 
        on_delete=models.PROTECT
    )
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo
        
    class Meta:
        app_label = 'app'

app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from app.models import Categoria, Pelicula

lista_categorias = [
            {'id': 1, 'nombre': 'Terror'},
            {'id': 2, 'nombre': 'Romance'},
            {'id': 3, 'nombre': 'Aventuras'},
            {'id': 4, 'nombre': 'Drama'},
            {'id': 5, 'nombre': 'Documental'},
        ]

def index(request):
    return render(request, 'app/index.html')

def categorias(request):
    # Obtiene todas las categorias
    lista_categorias = Categoria.objects.all()

    contexto = {
        'titulo': 'Blockbuster', 
        'categorias': lista_categorias,
    }
    return render(request, 'app/categorias.html', contexto)


def peliculas(request):
    return render(request, 'app/peliculas.html')


def categoria(request, id):
    return HttpResponse(f'Esta es la categoria {id}')


@login_required
def form_crear_categoria(request):
    return render(request, 'app/crearCategoria.html')


@login_required
def crear_categoria_post(request):
    # Obtiene los datos del cliente
    nombre = request.POST['nombre']

    # Crea la categoría en la BD
    categoria = Categoria()
    categoria.nombre = nombre
    categoria.save()

    return redirect('app:categorias')


@login_required
def form_crear_pelicula(request):
    # Obtiene las categorias
    categorias = Categoria.objects.all()
    # Crea el contexto
    contexto = {
        'categorias': categorias
    }
    return render(request, 'app/crearPelicula.html', contexto)


@login_required
def crear_pelicula_post(request):
    # Obtiene los datos del cliente
    titulo = request.POST['titulo']
    id_categoria = int(request.POST['categoria'])

    # Obtiene la categoria
    categoria = Categoria.objects.get(id=id_categoria)

    # Crea la pelicula
    pelicula = Pelicula()
    pelicula.titulo = titulo
    pelicula.categoria = categoria

    # Guarda la pelicula
    pelicula.save()

    return redirect('app:peliculas')


def form_iniciar_sesion(request):
    return render(request, 'app/login.html')


def iniciar_sesion(request):
    # Obtiene los datos del cliente
    username = request.POST['username']
    password = request.POST['password']

    # Obtiene el usuario
    usuario = authenticate(username=username, password=password)

    if usuario is not None:
        # Autentica el usuario en la plataforma
        login(request, usuario)
        return redirect('app:index')
    else:
        return redirect('app:form_iniciar_sesion')


def cerrar_sesion(request):
    logout(request)
    return redirect('app:index')

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block titulo %}Blockbuster{%endblock%}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;500;800&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="{% static 'app/css/estilo.css' %}" />
  </head>
  <body>
    <div class="contenedor">
      <header>
        <div class="logo">blockbuster</div>
        <div class="cuenta">
          <span>{{ request.user.first_name }}</span>
          <a href="{% url 'app:form_iniciar_sesion' %}">
            <i class="fa-solid fa-user"></i>
          </a>
        </div>
      </header>
      <nav>
        <ul>
          <li>
            <a href="{% url 'app:index' %}"
              ><i class="fa-solid fa-home"></i> Inicio</a
            >
          </li>
          <li>
            <a href="{% url 'app:categorias' %}"
              ><i class="fa-solid fa-tags"></i> Categorías</a
            >
          </li>
          <li>
            <a href="{% url 'app:peliculas' %}"
              ><i class="fa-solid fa-clapperboard"></i> Películas</a
            >
          </li>
          <li>
            <a href="{% url 'app:cerrar_sesion' %}"
              ><i class="fa-solid fa-person-walking-arrow-right"></i> Salir</a
            >
          </li>
        </ul>
      </nav>
      <div class="contenido">{% block contenido %} {% endblock %}</div>
    </div>
  </body>
</html>

app/templates/app/categorias.html
{% extends 'app/base.html' %} {% block contenido %}

<h1 class="encabezado">
  <span>Categorias</span>
  {% if request.user.is_authenticated %}
  <a class="button" href="{% url 'app:form_crear_categoria' %}"
    >Crear categoría</a
  >
  {% endif %}
</h1>

<ul id="lista-categorias">
  {% for categoria in categorias %}
  <li>
    <a href="{% url 'app:categoria' categoria.id %}">{{categoria.nombre}}</a>
  </li>
  {% endfor %}
</ul>

{% endblock %} {% block titulo %} Categorias {% endblock %}

app/templates/app/crearCategoria.html
{% extends 'app/base.html' %} {% block contenido %}
<h1>Crear Categoría</h1>
<hr />

<form action="{% url 'app:crear_categoria_post' %}" method="POST">
  {% csrf_token %}
  <fieldset>
    <label for="textNombre">Nombre</label>
    <input type="text" name="nombre" />
  </fieldset>
  <fieldset>
    <button>Crear</button>
  </fieldset>
</form>

{% endblock %}

app/templates/app/crearPelicula.html
{% extends 'app/base.html' %} {% block contenido %}
<h1>Crear Pelicula</h1>
<hr />

<form action="{% url 'app:crear_pelicula_post' %}" method="POST">
  {% csrf_token %}
  <fieldset>
    <label for="textTitulo">Titulo</label>
    <input type="text" name="titulo" />
  </fieldset>
  <fieldset>
    <label for="selectCategoria">Categoría</label>
    <select name="categoria">
      {% for categoria in categorias %}
      <option value="{{categoria.id}}">{{categoria.nombre}}</option>
      {% endfor %}
    </select>
  </fieldset>
  <fieldset>
    <button>Crear</button>
  </fieldset>
</form>

{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %} {% load static %} {% block contenido %}
<h1>Bienvenidos a Blockbuster</h1>
<div class="intro">
  <img
    id="banner"
    src="{% static 'app/img/last-blockbuster.webp' %}"
    alt="last"
  />
  <p>
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. In error quod
    ratione eveniet modi praesentium magnam perferendis. Officia velit, veniam
    eum nihil, impedit sint provident eveniet incidunt molestias temporibus
    deserunt.
  </p>
</div>
<hr />
<p>
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas, facilis?
</p>
{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %} {% load static %} {% block contenido %}
<h1>Ingresar a Blockbuster</h1>

<div class="login">

<form action="{% url 'app:iniciar_sesion' %}" method="POST">
  {% csrf_token %}
  <fieldset>
    <label for="username">Usuario</label>
    <input type="text" name="username">
  </fieldset>
  <fieldset>
    <label for="password">Contraseña</label>
    <input type="password" name="password">
  <fieldset>
  <fieldset>
    <button>Ingresar</button>
  </fieldset>
</form>

</div>


{% endblock %}

app/templates/app/peliculas.html
{% extends 'app/base.html' %} {% block contenido %}
<h1 class="encabezado">
  <span>Películas</span
  ><a class="button" href="{% url 'app:form_crear_pelicula' %}"
    >Crear película</a
  >
</h1>
{% endblock %}